# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IGListKitDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IGListKitDemo
  pod 'IGListKit', '~> 3.0'
  pod 'Masonry'
  pod 'MJRefresh'

  target 'IGListKitDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IGListKitDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
