# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  pod 'RongCloudIM/IMKit', '~> 5.1.2'
  pod 'RongCloudIM/IMLib', '~> 5.1.2'
  pod 'Masonry'
  pod 'AFNetworking'
  pod 'ReactiveObjC'
  pod 'MJExtension'
  pod 'YYKit'
  pod 'LookinServer', :configurations => ['Debug'] #界面查看工具
  pod 'MLeaksFinder', :configurations => ['Debug'] #检测内存泄漏
  pod 'TMUIKit', :git => 'https://github.com/chengzongxin/TMUIKit.git' #TMUI
  # Pods for IM

end
