# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WebViewDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WebViewDemo
#  pod 'VasSonic', '3.0.0'
#  pod 'SDWebImage'
  pod 'WebViewCache'

  target 'WebViewDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WebViewDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
