# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WRNavigationBarDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WRNavigationBarDemo
  pod 'WRNavigationBar'
  target 'WRNavigationBarDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WRNavigationBarDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
