# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TableViewHeader' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TableViewHeader
  pod 'LookinServer', :configurations => ['Debug'] #界面查看工具
  pod 'Masonry'

end
