# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AISkinMeasurement' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AISkinMeasurement
 	pod 'IGListKit'
  pod 'AFNetworking'

  target 'AISkinMeasurementTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AISkinMeasurementUITests' do
    # Pods for testing
  end

end
